version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: 'primeNumbers:1:1'

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: alfn
      CLICKHOUSE_PASSWORD: alfn
    volumes:
      - ./clickhouse/alfn/users.d:/etc/clickhouse-server/users.d/
      - ./clickhouse/alfn/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  processor:
    build: 
      context: .
      dockerfile: DockerfileProcessor
    container_name: processor
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - ./Processor.PrimeNumbers/appSettings.json:/Processor.PrimeNumbers/appSettings.json

  generator:
    build: 
      context: .
      dockerfile: DockerfileGenerator
    container_name: generator
    depends_on:
      - kafka
    volumes:
      - ./Generator.PrimeNumbers/appSettings.json:/Generator.PrimeNumbers/appSettings.json
      